### ISSUE TITLE
package-lint and check-doc warnings

### ISSUE THREAD

**Issue by danilshvalov** [nverno/sql-ts-mode#1]
Thanks for this wonderful package, I use it every day.

To add a package to MELPA, I runned [package-lint](https://github.com/purcell/package-lint) and it issued the following warnings:

> 2 issues found:
> 
> 8:3: warning: You should include standard keywords: see the variable `finder-known-keywords'.
> 27:0: error: Package should have a non-empty ;;; Commentary section.

Also `checkdoc` says that the following functions should have docstrings:
- `sql-ts-mode--select-term-parent`
- `sql-ts-mode--select-term-offset`

Could you fix them?

**Comment by nverno** [comment]
Hi, I'm glad it's working for you!

There are some tree-sitter features that still need to be implemented:
 - navigation: defining `treesit-defun-type-regexp`, `treesit-defun-name-function` and `treesit-thing-settings`
 - imenu: `treesit-simple-imenu-settings`
 
Have indentation and font-locking been working well for you? I haven't been using SQL recently, so haven't tested this very much yet.

**Comment by nverno** [comment]
I fixed the style warnings.

However, it looks like there is still a fair amount of font-locking + indentation stuff that is missing in addition to the navigation/imenu mentioned before.

**Comment by danilshvalov** [comment]
> Have indentation and font-locking been working well for you? I haven't been using SQL recently, so haven't tested this very much yet.

I didn't notice any problems when working with SQL. I'll test it again and if I find it, I'll create an issue.
